### ISSUE TITLE
add the ability to set different vm sizes for the different roles

### ISSUE THREAD

**Issue by raffaelespazzoli** [redhat-cop/casl-ansible#107]
add the ability to have different vm sizes for master, infranodes and nodes.

**Comment by oybed** [comment]
@raffaelespazzoli Thinking some more about this, you should be able to set these as-is with the ` lb_flavor`, `etcd_flavor`, `master_flavor`, `node_flavor`, `infra_flavor`, `dns_flavor` inventory variables. However, this need better documentation.

**Comment by raffaelespazzoli** [comment]
perfect then adding them to the example would serve well enough as documentation
