### ISSUE TITLE
upgrade to a RHEL 7.4 base image

### ISSUE THREAD

**Issue by raffaelespazzoli** [redhat-cop/casl-ansible#112]

**Comment by sabre1041** [comment]
@raffaelespazzoli you can change the `openstack_image` group variable to point to the 7.4 image. In the environment that you are using, it is `rhel-server-7.4-x86_64`. I'm testing it today and can submit a PR with any necessary changes

**Comment by oybed** [comment]
Yes, like @sabre1041 said, this is set by the `openstack_image` or `openstack_default_image_name` and is typically what we do for our customer inventories (i.e.: currently using RHEL 7.4). It could be good to update the sample inventories, however, to reflect RHEL 7.4. In general, we have a todo item to update the sample inventories and provide more commentary in there to better explain what these variables are for. 

Also; another item that would be beneficial, is to have different images per instance - i.e.: a DNS server based on a Fedora image v.s.: OpenShift's RHEL, etc.

**Comment by sabre1041** [comment]
@oybed I created #113 for us to start working on documenting the available options
