### ISSUE TITLE
Create a Tagged Release That Supports OpenShift Applier Filter Tags

### ISSUE THREAD

**Issue by sherl0cks** [redhat-cop/casl-ansible#137]
latest 3.6.1 release does not https://github.com/redhat-cop/casl-ansible/blob/v3.6.1/roles/openshift-applier/tasks/main.yml#L11

**Comment by oybed** [comment]
Release `v3.6.2` has been cut for various reasons. This includes the tags.
https://github.com/redhat-cop/casl-ansible/releases/tag/v3.6.2
