### ISSUE TITLE
Port heat stack implementation to os_* modules

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/casl-ansible#15]
Product direction is to steer away from individual clouds' provisioning/templating mechanisms. As such, we should replace our heat-based server provisioning with using the native ansible os_server, os_volume, etc.

**Comment by etsauer** [comment]
@oybed is this still something we want to do or can we close this issue?

**Comment by oybed** [comment]
@etsauer Ultimately I'd like to see us do both, but as discussed, going the os_* route may be a bit of a lower priority at the moment. I'm fine with closing this out and re-open a new issue if/when needed.
