### ISSUE TITLE
Variable name not consistent

### ISSUE THREAD

**Issue by makentenza** [redhat-cop/casl-ansible#158]
The variable used for dns domain in the OSP inventory example has different value in `all.yml` file and `OSEv3.yml` file:

https://github.com/redhat-cop/casl-ansible/blob/master/inventory/sample.osp.example.com.d/inventory/group_vars/all.yml#L52

https://github.com/redhat-cop/casl-ansible/blob/master/inventory/sample.osp.example.com.d/inventory/group_vars/OSEv3.yml#L27-L29

**Comment by oybed** [comment]
@makentenza please use the `resolves` keyword so we automatically close out issues when appropriate:
https://help.github.com/articles/closing-issues-using-keywords/
