### ISSUE TITLE
Variable to deploy metrics deprecated in 3.7

### ISSUE THREAD

**Issue by makentenza** [redhat-cop/casl-ansible#160]
The variable `openshift_hosted_metrics_deploy` can be removed for release 3.7 as is being deprecated in favour of `openshift_metrics_install_metrics` which is already included in sample inventories.

**Comment by oybed** [comment]
I presume you mean remove these from the sample inventory? If so, yes, they don't cause any harm, but it's good to do some clean-up.

https://github.com/redhat-cop/casl-ansible/blob/master/inventory/sample.osp.example.com.d/inventory/group_vars/OSEv3.yml#L53

https://github.com/redhat-cop/casl-ansible/blob/master/inventory/sample.aws.example.com.d/inventory/group_vars/OSEv3.yml#L54
