### ISSUE TITLE
support Amazon ELB in HA deployment

### ISSUE THREAD

**Issue by bagnaram** [redhat-cop/casl-ansible#225]
The ability to programatically deploy Amazon ELBs in HA configured deployments. Refer to the AWS reference architecture. https://access.redhat.com/documentation/en-us/reference_architectures/2017/

Work done on my branch: https://gitlab.consulting.redhat.com/spawarocp/casl-ansible

**Comment by oybed** [comment]
This should be possible to do with the rework done as part of PR https://github.com/redhat-cop/casl-ansible/pull/219

**Comment by makentenza** [comment]
solved in #219
