### ISSUE TITLE
Optionally install Logging and Metrics

### ISSUE THREAD

**Issue by bagnaram** [redhat-cop/casl-ansible#226]
In order to install metrics and logging components of openshift separate to the install. Add additional logic to `playbooks/openshift/install.yml`  to 
` - import_playbook: "{{ openshift_ansible_path | default('../../roles/openshift-ansible') }}/playbooks/byo/openshift-cluster/openshift-logging.yml"`

` - import_playbook: "{{ openshift_ansible_path | default('../../roles/openshift-ansible') }}/playbooks/byo/openshift-cluster/openshift-metrics.yml"
`

**Comment by oybed** [comment]
This should be possible to do just by setting the inventory correctly.

**Comment by oybed** [comment]
You can also run the above mentioned playbooks with the same inventory that you used to provision the cluster in the first place. From our discussion, it sounds like this will be sufficient - closing issue.
