### ISSUE TITLE
aws-provisioning: create elastic IP fails when deploy-cluster playbook is re-run

### ISSUE THREAD

**Issue by fzdarsky** [redhat-cop/casl-ansible#238]
When re-running the deploy-cluster.yml for AWS (as a first run failed with a config error), it fails with

```
TASK [manage-aws-infra : Create elastic IP for Master Node (Non HA Mode)] ******************************************************************
task path: /home/remote/fzdarsky/.ooo/casl-ansible/roles/manage-aws-infra/tasks/deploy-cluster.yml:234
fatal: [localhost]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: list object has no element 0\n\nThe error appears to have been in '/home/remote/fzdarsky/.ooo/casl-ansible/roles/manage-aws-infra/tasks/deploy-cluster.yml': line 234, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create elastic IP for Master Node (Non HA Mode)\n  ^ here\n"
}

```
The reason seems to be that the ec2 module used in create-instance.yml is not idempotent; it only returns newly created instances. Therefore, on the 2nd run it may return an empty master_instances list, leading to an index out of bound error in [deploy-cluster.yml line 237](https://github.com/redhat-cop/casl-ansible/blob/377bea0f0c7f47c0f10ca88067a36d1f61481c55/roles/manage-aws-infra/tasks/deploy-cluster.yml#L237).

**Comment by fzdarsky** [comment]
A work-around, of course, is to delete the cluster before re-running, as stated in the docs.

**Comment by oybed** [comment]
This is being addressed by PR https://github.com/redhat-cop/casl-ansible/pull/219
