### ISSUE TITLE
Can't pick up env details (Using docker) 

### ISSUE THREAD

**Issue by rmarcandier** [redhat-cop/casl-ansible#261]
Error:

TASK [manage-aws-infra : Fail when AWS KEY environment variables are not defined] *******************************************************************************************************************************************************************************************************************************************************************************************************************************************************
Thursday 21 June 2018  13:38:31 +0000 (0:00:00.047)       0:00:04.264 ********* 
fatal: [localhost]: FAILED! => {
    "failed_when_result": true, 
    "msg": "Both 'AWS_ACCESS_KEY_ID' and 'AWS_SECRET_ACCESS_KEY' environment variables must be defined"
}

PLAY RECAP ******************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=1   

---->>>

[rmarcand@localhost casl-ansible]$ env |grep -i AWS
AWS_SECRET_ACCESS_KEY=xxxxx
AWS_ACCESS_KEY=xxxxxx
AWS_ACCESS_KEY_ID=xxxxxxxx
[rmarcand@localhost casl-ansible]$

**Comment by makentenza** [comment]
@rmarcandier I think this was related to your terminal configuration and I checked with you how to solve this if I remember correctly. Can we close this issue?

**Comment by rmarcandier** [comment]
yes
