### ISSUE TITLE
Create role to tag images in OpenShift

### ISSUE THREAD

**Issue by oybed** [redhat-cop/casl-ansible#273]
This is a move of issue https://github.com/redhat-cop/openshift-applier/issues/26 to this repo since the referenced roles have moved here. Here's a copy/paste of the text in the original issue:

> I want to be able to tag images from different namespace and create labels on that new is in my given project.

**Comment by gmontalvoy** [comment]
Created https://github.com/redhat-cop/casl-ansible/pull/275 to address it.
