### ISSUE TITLE
BYO install failures if selinux starts on permissive

### ISSUE THREAD

**Issue by JayKayy** [redhat-cop/casl-ansible#292]
If selinux is change from permissive to enforcing/targeted no restorecon is run so services like sshd break as their configs are set to unlabelled and it gets permission denied accessing `/etc/ssh`.

`restorecon -r /etc` directory fixed our sshd service.

**Comment by JayKayy** [comment]
we may want to do a full restorecon to catch everything though.

**Comment by oybed** [comment]
@JayKayy I believe this has been taken care of with your PR for `infra-ansible`, so closing out the issue. Please re-open if you disagree.
