### ISSUE TITLE
BYO: 'dict object' has no attribute 'cns_node_glusterfs_volume' - OCS 3.10

### ISSUE THREAD

**Issue by darthlukan** [redhat-cop/casl-ansible#310]
This error occurs because there's no variable by that name defined in `/path/to/inventory/host_vars/localhost`. Previously, I had that variable in there as such:

```
cns_node_glusterfs_volume:
- "/dev/sdc"
- "/dev/sdd"
```
Which allowed me to not get this error, but triggered the error associated with [this issue](https://github.com/openshift/openshift-ansible/issues/5071), the fragile workaround for which is to remove global definitions of glusterfs devices.

The current behavior of `cns_node_glusterfs_volume` is that it only accepts a single device, which means it is in conflict with `glusterfs_devices` set in the host inventory when multiple devices are specified as a JSON array.

The suggested fix (via @oybed in external conversation) is two pronged:
1. `cns_node_glusterfs_volume` should do as intended and allow an array of devices to be specified.
2. `cns_node_glusterfs_volume` should be ignored in the `pre-install` playbook if `glusterfs_devices` is set in the hosts inventory.

This issue came up during a byo use-case. It may affect other use-cases if they include OCS 3.10.

**Comment by darthlukan** [comment]
@oybed - Can you please check this commit? It looks like the only place `cns_node_glusterfs_volume` is used in casl-ansible is to set the fact, which is handed off later to infra-ansible and/or openshift-ansible, so any "array vs single value" handling would have to be done in those places, not here. That said, that commit applies the ignore logic, essentially: "set fact when `glusterfs_devices` is not defined or `glusterfs_devices` has a length of 0".

**Comment by oybed** [comment]
@darthlukan please submit a PR and we can follow the normal PR review process. 

All changes needed for this issue should be handled here:
https://github.com/redhat-cop/casl-ansible/blob/master/playbooks/openshift/pre-install.yml#L70-L74
