### ISSUE TITLE
BYO: pre-install playbook does not set glusterfs_devices fact for glusterfs_registry group

### ISSUE THREAD

**Issue by darthlukan** [redhat-cop/casl-ansible#313]
Currently the pre-install playbook sets the `glusterfs_devices` fact using the `cns_node_glusterfs_volume` variable in use via `host_vars/localhost`. However, it only does this for `glusterfs` node group, not for `glusterfs_registry`. This causes the installation to fail fatally when using glusterfs_registry as part of the cluster.

In our particular use-case (single device `/dev/sdX` for both glusterfs and glusterfs_registry), we edited the playbook directly to also include the registry group, e.g.: `- hosts: glusterfs,glusterfs_registry`.

Our solution works fine for this specific use-case, but would be unusable in a multi-device context due to the current behavior of `cns_node_glusterfs_volume` only handling a single device. It would fall apart even more if we were to require multiple devices for glusterfs and multiple different devices for glusterfs_registry, e.g. `glusterfs: [/dev/sdc, /dev/sdd], glusterfs_registry: [/dev/sde, /dev/sdf]`

A possible workaround might be to make the tasks for glusterfs pre-install toggleable via a variable, or to allow the specification of multiple specific variables, e.g. `cns_node_glusterfs_volumes` for glusterfs and `cns_node_glusterfs_registry_volumes` for glusterfs_registry, with the same logic as is present in the latest iteration of the play (recently accepted pull request 311).

All of this was noted using the latest casl-ansible with OCP 3.10 and OCS 3.10 in converged mode.

**Comment by oybed** [comment]
In general, for BYO I'd recommend just setting `glusterfs_devices` and `glusterfs_registry` as part of the inventory and be done - i.e.: no need to go through additional steps of setting `cns_*` variables, etc.  (this is for uses cases where an IaaS, such as AWS is utilized and there's a need to dynamically obtain the names of these devices as they aren't known up front). 

Setting `glusterfs_registry` is a good call out for something that should be part of issue #266 (and broader support for CNS - or OCS rather - as part of CASL).

**Comment by oybed** [comment]
Per our discussion, closing this issue.
