### ISSUE TITLE
aws-provisioning: Should we support MFA tokens?

### ISSUE THREAD

**Issue by jtudelag** [redhat-cop/casl-ansible#314]
If MFA is enabled and enforced in the API, **aws_access_key** & **aws_secret_key** would not be enough to provision the infra, so we would need a MFA session token as well ;)

Please someone correct me If I'm wrong.

* https://aws.amazon.com/premiumsupport/knowledge-center/authenticate-mfa-cli/
* https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_mfa_configure-api-require.html

**Comment by makentenza** [comment]
This is true, but also true that we didn't have this requirement so far from anyone. From my point of view we could just point to the [link](https://aws.amazon.com/premiumsupport/knowledge-center/authenticate-mfa-cli/) you mentioned in CASL AWS documentation for anyone who wants to implement or require a token.

What do you think @oybed @etsauer?

**Comment by jtudelag** [comment]
Closing this ;)
