### ISSUE TITLE
Create a Docker image relase of CASL ansible

### ISSUE THREAD

**Issue by ckyriakidou** [redhat-cop/casl-ansible#321]
OSE-ansible comes packaged as a docker image, CASL ansible could do the same based on that image. This would mean that most (if not all) the dependencies are packaged as a release and each artifact is usable as such. We could do a github/dockerhub integration or any other integration that would allow consumers to just download the image tar.

**Comment by oybed** [comment]
@ckyriakidou we already create images for casl-ansible - currently found on docker hub [installer-openstack]https://hub.docker.com/r/redhatcop/installer-openstack/) & [installer-aws](https://hub.docker.com/r/redhatcop/installer-aws/). The source for these images can be found in the [images](https://github.com/redhat-cop/casl-ansible/tree/master/images) area.

Having said that, we are looking to re-do these images in the near future (work already in progress), for a few reasons:
- Move to [quay.io](https://quay.io)
- Combine all images for this repo into one (the differences are minor, so no need to keep them separate)
- Allow for newer versions.
- Clean-up of docs and better alignment between each IaaS target

If you have any additional suggestions for additional functionality, please let us know. Now would be a perfect timing.

**Comment by ckyriakidou** [comment]
I think it's missing a byo one. Openstack and AWS are not necessarily what you need when you're building something that is not on the public cloud or a private openstack cloud. I also really like the ansible-galaxy way of installing things as it versions things. What do you think? I've moved it to images/casl-byo and testing it at the moment.

**Comment by oybed** [comment]
@ckyriakidou thanks again for your input. The BYO can be done with any of the container images we have as it doesn't have any specific requirements beyond what those containers already provide. As mentioned above, we are moving towards a consolidated container image, and it will be also be usable for the BYO scenarios.
