### ISSUE TITLE
Add config-lvm pre-req step

### ISSUE THREAD

**Issue by duritong** [redhat-cop/casl-ansible#322]
So we can configure lvm volumes as part of the pre-req steps.

https://github.com/redhat-cop/casl-ansible/blob/master/playbooks/openshift/pre-install.yml#L41

**Comment by oybed** [comment]
@duritong can you please be a bit more specific on what these LVMs are for? We can add the call to `config-lvm`, and use the inventory to drive it, but it would be useful to know more details about the use-case to ensure the requirements are met. 

Thx

**Comment by duritong** [comment]
@ckyriakidou and I ware working on a patch for that. We need to provide storage for /var/lib/etcd (on masters), /var/lib/origin/openshift.local.volumes (to use quota for emptydir etc.)
