### ISSUE TITLE
Update docs/PROVISIONING_*.md to use new installer image

### ISSUE THREAD

**Issue by tylerauerbeck** [redhat-cop/casl-ansible#338]
The `docs/PROVISIONING_OPENSTACK.md` files still appear to be referring to the old container image. This should be updated to point to the new image (`quay.io/redhat-cop/casl-ansible`)

**Comment by bvkin** [comment]
Hey so I looked through those files and I didn't see anything that looked like it should be pointing to quay.io. I did however see some broken links for our container image file within the repo. Is that what you were referring to?
