### ISSUE TITLE
Subscription-Manager role not idempotent when it comes to enabling repos

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/casl-ansible#35]
If I add or remote yum repos from the list, our role does not recognize that there are changes to be made. We currently do the enabling of repos using commands rather than modules because the modules don't support it yet.

There is an open issue in ansible-core-modules about adding it. https://github.com/ansible/ansible-modules-core/issues/3300

**Comment by oybed** [comment]
here's an implementation done to selectively disable/enable repos based on the currently enabled repos v.s. what is supposed to be enabled:
https://github.com/redhat-cop/infra-ansible/blob/master/roles/rhsm/tasks/main.yml#L10-L20
