### ISSUE TITLE
openstack-stack role should name the heat stack with env_id + cluster_id

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/casl-ansible#36]
Currently we name heat stacks with `env_id`, like `l1/d1/a1` etc. However, `env_id` often repeats across `cluster_id`s. This prevents me from standing up an `l1` cluster in two different `dns_domains`.

**Comment by oybed** [comment]
I'd also like to see the option to include another unique identifier to allow for multiple clusters of the same name without impacting the environment id / DNS names. I.e.: something like:
```
- l1.example.com-blue
- l1.example.com-green
```
This could be useful for a blue/green type of scenario where you'd want your final cluster to have the same DNS records, hence don't want to set a blue/green name as part of the `env_id` or `dns_domain`.
