### ISSUE TITLE
Unsupported parameters for (openshift_facts)

### ISSUE THREAD

**Issue by brandonwilliamsised** [redhat-cop/casl-ansible#368]
Building a 1x1x1 cluster on AWS, receiving the following in [TASK Gather Cluster Facts]:

```
  1. Hosts:    100.96.198.11, 100.96.198.16, 100.96.198.30
     Play:     Initialize cluster facts
     Task:     Gather Cluster facts
     Message:  Unsupported parameters for (openshift_facts) module: system_facts Supported parameters include: additive_facts_to_overwrite, attributes, backup, content, delimiter, directory_mode, follow, force, group, local_facts, mode, owner, regexp, remote_src, role, selevel, serole, setype, seuser, src, unsafe_writes
```
Previously I was able to build successfully with the same configuration.

Possible relation to openshift-ansible commit https://github.com/openshift/openshift-ansible/commit/9b2b62f1182320d00ce10aef5eaae09fc03c4454 ? 

I'm using casl-ansible master, with `casl-requirements.yml` specifying openshift-ansible `release-3.11`, executing via the `quay.io/redhat-cop/casl-ansible` docker image.

Any help would be greatly appreciated!

**Comment by brandonwilliamsised** [comment]
Confirmed that downgrading openshift-ansible from `release-3.11` to commit https://github.com/openshift/openshift-ansible/commit/592b66ae72fe6cdb7dfba16a8591192e017caf29 allows execution to continue.

**Comment by oybed** [comment]
The `casl-requirements` file is a suggested pairing of versions, and yes, the `release-3.11` has a tendency to break. There's really no good process in place to keep the requirements file in sync with "working" openshift-ansible commits, so it's a bit of a best effort approach. It's encouraged for the user to keep a list of working releases/commits with their specific use case - for the most part the `release-3.11` is sufficient for this.
