### ISSUE TITLE
projectrequest feature of openshift-applier not idempotent

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/casl-ansible#84]
The second time running through an openshift-applier role on a cluster, ansible fails, citing "Project already exists" error message. Need to figure out how to handle this.

@oybed @day4skiing

**Comment by sherl0cks** [comment]
I hit this today as well. It's related to the fact that the role uses `oc create`, not `oc apply` for `projectrequest`, though it seems that `oc apply` for `projectrequests` requires more permissions

**Comment by sherl0cks** [comment]
@oybed @etsauer this is a blocker for me. I hacked a work around by ensuring the `name` in the inventory matches the name in the `ProjectRequest` object. Then I added the below to `handle-projectrequest.yml`. It's ugly - but it gets the job done:

```
- name: "Determine If {{ entry.content[0].name }} Project Exists"
  command: >
     oc get project {{ entry.content[0].name }} -o json
  register: project_name_taken
  failed_when: false
  changed_when: false

```

Happy to submit a PR, though I suspect we want a cleaner solution
