### ISSUE TITLE
Update create_users role to be optional.

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/casl-ansible#9]
The use of `is defined` in a conditional is not valid, as null variables still cause failure. we need to instead do some kind of boolean to decided whether tasks in a role should be run.

http://docs.ansible.com/ansible/playbooks_conditionals.html#applying-when-to-roles-and-includes

Something like:
`when: users_to_create | default({}) | length >= 1`

**Comment by oybed** [comment]
@etsauer is this issue still required? ... or can it be closed out?
